### ISSUE TITLE
当会话窗口到底部时收到图片会被输入框遮挡一半

### ISSUE THREAD

**Issue by HuaZao** [ws00801526/XMChatBarExample#10]
![simulator screen shot 2015 11 25 3 16 53](https://cloud.githubusercontent.com/assets/13476604/11401196/5351af6e-93cc-11e5-907b-d229a8c8c739.png)
![simulator screen shot 2015 11 25 3 16 53](https://cloud.githubusercontent.com/assets/13476604/11401196/5351af6e-93cc-11e5-907b-d229a8c8c739.png)

**Comment by ws00801526** [comment]
你使用的版本是 1.2.2的么?

**Comment by HuaZao** [comment]
最新的版本,还有发送失败状态也不显示

**Comment by ws00801526** [comment]
能加下QQ么?  3057600441
