### ISSUE TITLE
录音失败

### ISSUE THREAD

**Issue by DsdaliOS** [ws00801526/XMChatBarExample#15]
作者你好，我是直接拖拽到我工程里的，录音不管多少秒最后都会显示录音失败是怎么回事儿啊？

**Comment by DsdaliOS** [comment]
图片想要点开查看是不是要自己加啊？

**Comment by ws00801526** [comment]
是的呢

**Comment by DsdaliOS** [comment]
作者你好，我想显示出来我接收的消息为对方对话没有显示出来，根据断点显示是没有走到XMNChatViewModel类的- (void)recieveMessage:(NSDictionary *)message方法里面来，这是为什么啊？

**Comment by ws00801526** [comment]
显示接收消息的流程应该是下面这个,您对照下对不对
chatServer(receiveMessage) -> 调用chatServerDelegate -> 通知chatVM addMessage -> 通知tableView reload刷新数据

**Comment by DsdaliOS** [comment]
你好，我挪用到我的工程里，在我接收消息的类里面写上了XMNChatServer协议，然后用 [self.delegate recieveMessage:messageDict];去调用，但是断电显示，可以走到XMNChatServer.h里面，但是却调用不了XMNChatVM里面的recieveMessage方法，这是什么原因啊？

**Comment by ws00801526** [comment]
Hi,你可以看下XMChatViewModel这个类中的initWithParentVC  其中吧_chatServer 更改成你写的chatServer

**Comment by DsdaliOS** [comment]
我把那里面的_chatServer = [[XMNChatServerExample alloc] init];改为了_chatServer = [[MessageManger alloc] init]; MessageManger是我接收消息的NSobjc类

**Comment by DsdaliOS** [comment]
已解决，我自己改成了通知调用
