### ISSUE TITLE
接收音频消息不能播放

### ISSUE THREAD

**Issue by DsdaliOS** [ws00801526/XMChatBarExample#16]
楼主你好，我接收的mp3格式的音频消息，
 messageDict[kXMNMessageConfigurationVoiceKey]
 messageDict[kXMNMessageConfigurationVoiceSecondsKey]
分别给了url和时长，但是展示到tableview上面点击没有声音，而且那个播放动画会一直存在，自己这边发送是没有问题的。是不是接收的时候,文件名字也要改成类似于发送时候那样的？

**Comment by ws00801526** [comment]
你可以断点 XMNAVAudioPlayer  看下是否下载成功了,播放的时候只能播放iOS支持的音频格式 MP3,caf等  AMR是不行的

**Comment by DsdaliOS** [comment]
现在的情况是iOS接收苹果手机发送的语音消息可以正常播放，但是接收安卓的就是我说的那种情况，安卓发送的语音消息已经改成了mp3的格式，url也是.mp3的。这有可能是什么原因呢？

**Comment by ws00801526** [comment]
不知道你那边改格式是怎么改的,android录音完毕之后应该也是需要转码MP3的  .. iOS这边这个版本录音的采样率是8000  你可以问下android那边的采样率是多少
这边有个Audio播放的  支持AMR编码解码播放 你可以参考下 [XMNAudio](https://github.com/ws00801526/XMNAudio)

**Comment by ws00801526** [comment]
新版本实用XMNAudio 进行录音,播放  可编码MP3,AMR,caf 等格式
