### ISSUE TITLE
图本被挡问题

### ISSUE THREAD

**Issue by mingyunjianzhushi** [ws00801526/XMChatBarExample#17]
请问一下，弹出键盘时候，会遮挡图文这个情况，我没想到好的解决办法，请问您有吗

**Comment by ws00801526** [comment]
不好意思,这是版本bug,暂时没法解决, 稍后我上传个新版本的XMNChatBar,重写了  但是功能还未全部完成

**Comment by ws00801526** [comment]
已经提交最新的版本了,可以查看下
