### ISSUE TITLE
总是录音失败

### ISSUE THREAD

**Issue by dajun512** [ws00801526/XMChatBarExample#22]
XMNChatController+XMNVoice.m:192    recorder error :Error Domain=com.XMFraker.XMNAudioRecorder.kXMNAudioRecorderErrorDomain Code=3 "音频队列开始录音失败" UserInfo={NSLocalizedDescription=音频队列开始录音失败}

**Comment by ws00801526** [comment]
是不是iOS 新版本 权限未添加?
