### ISSUE TITLE
每次收到新的消息之后，对tableView进行reloadData，开销是很大的

### ISSUE THREAD

**Issue by PonyCui** [ws00801526/XMChatBarExample#4]
这就是为什么我使用AsyncDisplayKit的原因，几乎所有的聊天界面库使用的都是传统的UITableView，UITableView在insert一个cell或是reloadData的时候，都需要很大的开销，当你的消息数目达到一定量级时，每收一条消息就需要等候很长的时间。

**Comment by ws00801526** [comment]
非常感谢解答, 我去试下,这个类库没用过
