### ISSUE TITLE
表情功能没有适配好

### ISSUE THREAD

**Issue by yslwjj** [ws00801526/XMChatBarExample#6]
在6s plus上面已经错位了。

**Comment by ws00801526** [comment]
hi,因为我没有添加设备判断,你可以进行下设备判断,如下图,5s返回6,6plus返回7就表情就可以适配了
![619d73bc-3578-4a9c-a764-9715d38a54af](https://cloud.githubusercontent.com/assets/3012567/10186961/85bbf9ee-6787-11e5-9b64-b2cdbffdfd6b.png)
